/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

// kernel/src/harvester/observations.ts — Phase 5 Plan 05-03 + Phase 6 Plan 06-05.
//
// RawObservation discriminated-union Zod schema. Single source of truth across the
// kernel + bridge. The bridge mirror in
// src/vs/goatide/extensions/goatide-bridge/src/kernel/methods.ts re-declares the SHAPE
// (CJS<->ESM constraint per Plan 04-05); structural identity is the contract.
//
// Five sources today (after Plan 06-05):
//   - claude_jsonl, editor_save, terminal_shell, git_commit (Phase 5 — Plan 05-03 + 05-04)
//   - mcp_external_signal (Phase 6 — Plan 06-05; ADDITIVE, back-compat preserved)
//
// Plan 06-05 ADDS the `mcp_external_signal` branch ONLY. Existing 4 branches unchanged so
// Phase-5 watchers (claude_jsonl, editor_save, terminal_shell, git_commit) keep parsing as
// before. Zod's discriminatedUnion strict-on-source ensures unknown source values still
// throw — refuse-fuzzy-fallback.sh + structural pin tests verify.

import { z } from 'zod';

const Base = z.object({
	id: z.string(),                                   // ulid; generated by the watcher or RPC handler
	ts: z.string(),                                   // ISO-8601
	body: z.string(),                                 // raw or normalized payload text
});

/** TELE-01 — one Claude assistant transcript line per JSONL entry. */
export const ClaudeJsonlObservationSchema = Base.extend({
	source: z.literal('claude_jsonl'),
	file_path: z.string(),                            // absolute path to the JSONL file
	parsed: z.unknown().optional(),                   // forgiving — JSONL schema evolves
});
export type ClaudeJsonlObservation = z.infer<typeof ClaudeJsonlObservationSchema>;

/** TELE-02 — coarse editor-save observation (line_count + language; never per-keystroke). */
export const EditorSaveObservationSchema = Base.extend({
	source: z.literal('editor_save'),
	file_path: z.string(),
	language: z.string(),
	line_count: z.number().int().nonnegative(),
	detail: z.object({ working_set_size: z.number().int().nonnegative() }).optional(),
});
export type EditorSaveObservation = z.infer<typeof EditorSaveObservationSchema>;

/** TELE-03 — terminal shell-execution end event with normalized output. */
export const TerminalShellObservationSchema = Base.extend({
	source: z.literal('terminal_shell'),
	output: z.string(),
	exit_code: z.number().int().nullable(),
	cwd: z.string().nullable(),
	detail: z.object({ confidence: z.number().int().nonnegative(), truncated: z.boolean() }).optional(),
});
export type TerminalShellObservation = z.infer<typeof TerminalShellObservationSchema>;

/** TELE-04 — git commit observation. Bridge sends the thin shape; kernel-side
 *  enrichGitCommitObservation populates {diff, message, author, files_changed} BEFORE
 *  the filter pipeline (Plan 05-05) sees it. */
export const GitCommitObservationSchema = Base.extend({
	source: z.literal('git_commit'),
	repo_path: z.string(),
	head_commit_at_emit: z.string().nullable(),
	head_branch_at_emit: z.string().nullable(),
	diff: z.string().optional(),
	message: z.string().optional(),
	author: z.string().optional(),
	files_changed: z.number().int().nonnegative().optional(),
});
export type GitCommitObservation = z.infer<typeof GitCommitObservationSchema>;

/**
 * MCP-04/05 (Phase 6 Plan 06-05) — external MCP signal observation.
 *
 * Wire shape for tool-call results harvested via the Phase-6 MCP consume side. The provider
 * + tool_name discriminate on the upstream source; the optional detail.candidate_node_kind_hint
 * is consumed by the Phase-5 PORT-04 Promoter as a system-prompt bias (NOT an authoritative
 * override per Open Question 6 of 06-RESEARCH.md). The hint never bypasses the Promoter
 * (Mandate-A — auditable+replayable classification).
 */
export const McpExternalSignalObservationSchema = Base.extend({
	source: z.literal('mcp_external_signal'),
	provider: z.enum(['github', 'slack', 'linear', 'jira']),
	tool_name: z.string(),
	detail: z.object({
		candidate_node_kind_hint: z.enum(['ConstraintNode', 'DecisionNode', 'ContractNode', 'OpenQuestion']).nullable().optional(),
	}).passthrough().optional(),
});
export type McpExternalSignalObservation = z.infer<typeof McpExternalSignalObservationSchema>;

/** Discriminated-union over all five source variants. Used at the RPC boundary
 *  (kernel/src/rpc/server.ts SubmitObservationRequest handler) for Zod validation, and by
 *  the Phase-6 observation-router for routing MCP tool-call results through the Phase-5
 *  6-gate cascade unchanged. */
export const RawObservationSchema = z.discriminatedUnion('source', [
	ClaudeJsonlObservationSchema,
	EditorSaveObservationSchema,
	TerminalShellObservationSchema,
	GitCommitObservationSchema,
	McpExternalSignalObservationSchema,
]);
export type RawObservation = z.infer<typeof RawObservationSchema>;
export type ObservationSource = RawObservation['source'];
