/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

// kernel/src/harvester/observations.ts — Phase 5 Plan 05-03.
//
// RawObservation discriminated-union Zod schema. Single source of truth across the
// kernel + bridge. The bridge mirror in
// src/vs/goatide/extensions/goatide-bridge/src/kernel/methods.ts re-declares the SHAPE
// (CJS<->ESM constraint per Plan 04-05); structural identity is the contract.
//
// Four sources today: claude_jsonl, editor_save, terminal_shell, git_commit. Plan 05-04
// adds APPEND-ONLY enrichment fields to the terminal_shell branch (NOT replacement).

import { z } from 'zod';

const Base = z.object({
	id: z.string(),                                   // ulid; generated by the watcher or RPC handler
	ts: z.string(),                                   // ISO-8601
	body: z.string(),                                 // raw or normalized payload text
});

/** TELE-01 — one Claude assistant transcript line per JSONL entry. */
export const ClaudeJsonlObservationSchema = Base.extend({
	source: z.literal('claude_jsonl'),
	file_path: z.string(),                            // absolute path to the JSONL file
	parsed: z.unknown().optional(),                   // forgiving — JSONL schema evolves
});
export type ClaudeJsonlObservation = z.infer<typeof ClaudeJsonlObservationSchema>;

/** TELE-02 — coarse editor-save observation (line_count + language; never per-keystroke). */
export const EditorSaveObservationSchema = Base.extend({
	source: z.literal('editor_save'),
	file_path: z.string(),
	language: z.string(),
	line_count: z.number().int().nonnegative(),
	detail: z.object({ working_set_size: z.number().int().nonnegative() }).optional(),
});
export type EditorSaveObservation = z.infer<typeof EditorSaveObservationSchema>;

/** TELE-03 — terminal shell-execution end event with normalized output. */
export const TerminalShellObservationSchema = Base.extend({
	source: z.literal('terminal_shell'),
	output: z.string(),
	exit_code: z.number().int().nullable(),
	cwd: z.string().nullable(),
	detail: z.object({ confidence: z.number().int().nonnegative(), truncated: z.boolean() }).optional(),
});
export type TerminalShellObservation = z.infer<typeof TerminalShellObservationSchema>;

/** TELE-04 — git commit observation. Bridge sends the thin shape; kernel-side
 *  enrichGitCommitObservation populates {diff, message, author, files_changed} BEFORE
 *  the filter pipeline (Plan 05-05) sees it. */
export const GitCommitObservationSchema = Base.extend({
	source: z.literal('git_commit'),
	repo_path: z.string(),
	head_commit_at_emit: z.string().nullable(),
	head_branch_at_emit: z.string().nullable(),
	diff: z.string().optional(),
	message: z.string().optional(),
	author: z.string().optional(),
	files_changed: z.number().int().nonnegative().optional(),
});
export type GitCommitObservation = z.infer<typeof GitCommitObservationSchema>;

/** Discriminated-union over all four source variants. Used at the RPC boundary
 *  (kernel/src/rpc/server.ts SubmitObservationRequest handler) for Zod validation. */
export const RawObservationSchema = z.discriminatedUnion('source', [
	ClaudeJsonlObservationSchema,
	EditorSaveObservationSchema,
	TerminalShellObservationSchema,
	GitCommitObservationSchema,
]);
export type RawObservation = z.infer<typeof RawObservationSchema>;
export type ObservationSource = RawObservation['source'];
